#!/bin/bash
#PBS -l walltime=1:00:00,select=1:ncpus=1:ngpus=1:gpu_mem=32gb
#PBS -N FirstJobBasedOnVenv_Faramarz
#PBS -m abe
#PBS -M jabbarva@ece.ubc.ca
#PBS -A st-lampe-1-gpu
#PBS -o /scratch/st-lampe-1/Faramarz/outputs/output.txt
#PBS -e /scratch/st-lampe-1/Faramarz/outputs/error.txt


#module load miniconda3
source activate /home/jabbarva/miniconda3/envs/tf_gpu


#module unuse /arc/software/spack/share/spack/lmod/linux-centos7-x86_64/Core
#module use /arc/software/spack-0.14.0-110/share/spack/lmod/linux-centos7-x86_64/Core
#module load openmpi/3.1.5 openblas/0.3.9 cuda/10.2.89 py-keras/2.2.4-py3.6.8 miniconda3/4.8.3 python/3.6.8 

#source ~/.bashrc


python -u /scratch/st-lampe-1/Faramarz/my_code/main_for_arc.py > /scratch/st-lampe-1/Faramarz/outputs/temporary_output_"`date +"%Y_%m_%d_%H_%M.txt"`"

#python /scratch/st-lampe-1/Faramarz/my_code/main_for_arc.py