#!/bin/bash

#PBS -l walltime=00:10:00,select=1:ncpus=8:ngpus=1:mem=32gb
#PBS -N FirstJobFara
#PBS -M jabbarva@ece.ubc.ca
#PBS -A st-lampe-1-gpu
#PBS -o /scratch/st-lampe-1/Faramarz/output.txt
#PBS -e /scratch/st-lampe-1/Faramarz/error.txt



module unuse /arc/software/spack/share/spack/lmod/linux-centos7-x86_64/Core
module use /arc/software/spack-0.14.0-110/share/spack/lmod/linux-centos7-x86_64/Core
module load openmpi/3.1.5 openblas/0.3.9 cuda/10.2.89 py-keras/2.2.4-py3.6.8 miniconda3/4.8.3 python/3.6.8

#module load python3 miniconda3 cuda

#cd /scratch/st-lampe-1/Faramarz

source ~/.bashrc
source activate /home/jabbarva/miniconda3/envs/Jabbarvaziri_environment



python -u /scratch/st-lampe-1/Faramarz/main_for_arc.py > /scratch/st-lampe-1/Faramarz/temporary_output_"`date +"%Y_%m_%d_%H_%M.txt"`"